name: Trivy test
on:
  pull_request:
    paths:
      - '**/*.tf'
jobs:
  trivy:
    name: Trivy test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run Trivy vulnerability scanner in fs mode
      uses: aquasecurity/trivy-action@0.28.0
      with:
        scan-type: 'config'
        format: 'sarif'
        output: 'trivy-result.sarif'
        exit-code: '0'
        severity: 'CRITICAL,HIGH'
    - name: Post SARIF findings in the issue
      uses: sett-and-hive/sarif-to-issue-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ github.repository }}
        branch: ${{ github.head_ref }}
        pr-number: ${{ github.event.number }}
        sarif-file: 'trivy-result.sarif'
        title: 'Security scanning results'
        odc-sarif: false

