name: Trivy test
on:
  pull_request:
    paths:
      - '**/*.tf'
jobs:
  trivy:
    name: Trivy test
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run trivy with reviewdog output on the PR
      uses: reviewdog/action-trivy@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        trivy_command: config # Change trivy command
        trivy_target: "${{ github.workspace }}/terraform" # Change trivy target directory
        trivy_flag: "--severity CRITICAL"
        level: error # Get more output from reviewdog
        reporter: github-pr-review # Change reviewdog reporter
        fail_level: error # Fail action if any level of failures are found
